root_type: node
beam_size: 10
use_random_simulate: false
max_coeff_num: 5
max_token_num: 30
c_puct: 5.0
tempreture: 0.0
lambda_rollout: 0.5
log_per_episode: 10
complexity_base: 0.999
sample_num: 500
early_stop_acc4: 0.99
unguided_comparison: true
